import { el, list, paragraphs } from "./dom.js";

export function confidenceSummary(report, analysis) { if (analysis?.source === "local") return { label: "Medium", detail: "Estimated locally from the current page." }; if (analysis?.policy) return { label: "High", detail: "Page, network, and policy evidence were analyzed." }; return { label: report?.thirdParties?.length ? "Medium" : "Low", detail: "Based on the current page scan." }; }
export function friendlyCategory(value) { const map = { ads: "Advertising", analytics: "Analytics", identity: "Sign-in / identity", consent: "Consent tools", risk: "Risk / fingerprinting" }; return map[value] || (value || "Unknown"); }
export function resolvePartyIntel(party, domainIntel = []) { const fallback = domainIntel.find((item) => item.host === party.host) || {}; const known = Boolean(party.known || fallback.known); return { ...party, company: party.company || fallback.company || "Unclassified third party", category: party.category || party.categories?.[0] || fallback.category || "unknown", risk: party.risk || fallback.risk || "unknown", known }; }
export function renderOverview(report, analysis, onAction) { const score = report?.risk?.score || 0; const level = String(report?.risk?.level || "Low"); const services = report?.thirdParties?.length || 0; el("decisionSummary").className = `decision ${level.toLowerCase()}`; el("riskCard").className = `risk ${level.toLowerCase()}`; el("decisionVerdict").textContent = level === "High" ? "Pause and review" : level === "Medium" ? "Use caution" : "No urgent concern"; el("decisionText").textContent = services ? `Your browser contacted ${services} outside service${services === 1 ? "" : "s"}.` : "This scan did not find an outside service."; el("riskLevel").textContent = level; el("riskScore").textContent = `${score}/100`; el("riskMeter").style.width = `${score}%`; const risks = [...new Set(report?.risk?.reasons || [])].slice(0, 3); const target = el("decisionRisks"); target.replaceChildren(...risks.map((item) => { const chip = document.createElement("span"); chip.className = "chipButton"; chip.textContent = item; return chip; })); const actions = el("decisionActions"); actions.replaceChildren(...["Review policy", "What can I do?"].map((label) => { const button = document.createElement("button"); button.type = "button"; button.className = "chipButton actionChip"; button.textContent = label; button.onclick = () => onAction(label); return button; })); paragraphs("plainEnglish", report?.plainEnglish?.summary || [services ? `Observed ${services} outside services on this page.` : "No outside services observed yet."]); list("dataCollected", report?.plainEnglish?.dataCollected, "No clear data collection signal found."); list("sharedWith", report?.plainEnglish?.sharedWith, "No clear sharing signal found."); renderStats(report?.risk); renderThirdParties(report?.thirdParties || []); renderLinks(report?.content?.policyLinks, report?.content?.inferredPolicyLinks); }
function renderStats(risk = {}) { const node = el("stats"); node.replaceChildren(); [["Third-party domains", risk.counts?.thirdPartyDomains || 0], ["Known trackers", risk.counts?.knownTrackerDomains || 0], ["Ad domains", risk.counts?.adDomains || 0]].forEach(([label, value]) => { const card = document.createElement("div"); card.className = "stat"; card.innerHTML = ""; const strong = document.createElement("strong"); strong.textContent = value; const span = document.createElement("span"); span.textContent = label; card.append(strong, span); node.appendChild(card); }); }
function renderThirdParties(parties) { const node = el("thirdParties"); node.replaceChildren(); if (!parties.length) { const li = document.createElement("li"); li.textContent = "No third-party requests observed yet."; node.appendChild(li); return; } parties.forEach((party) => { const li = document.createElement("li"); li.textContent = `${party.host} — ${party.company || "Unclassified third party"} (${party.count || 0} requests)`; node.appendChild(li); }); }
function renderLinks(links = [], inferred = []) { const node = el("policyLinks"); node.replaceChildren(); const all = [...(links || []), ...(inferred || [])]; if (!all.length) { const li = document.createElement("li"); li.textContent = "No privacy-policy link was detected."; node.appendChild(li); return; } all.slice(0, 8).forEach((link) => { const li = document.createElement("li"); const a = document.createElement("a"); a.href = link.href; a.target = "_blank"; a.rel = "noreferrer"; a.textContent = link.text || link.href; li.appendChild(a); node.appendChild(li); }); }
