import { el } from "./dom.js";

export function labelItem(title, value, detail) { const box = document.createElement("div"); box.className = "labelItem"; const strong = document.createElement("strong"); strong.textContent = value; const span = document.createElement("span"); span.textContent = detail ? `${title}: ${detail}` : title; box.append(strong, span); return box; }
export function localDataCollectedSummary(report) { const values = new Set(); if (report?.content?.oauth?.hasOAuthProvider || report?.content?.oauth?.scopes?.length) values.add("account access"); if (report?.content?.fingerprinting?.detected) values.add("device or browser identifiers"); if (report?.risk?.reasons?.some((reason) => /cookie banner/i.test(reason))) values.add("cookie and consent preferences"); if (report?.thirdParties?.length) values.add("browsing activity and page interactions"); (report?.content?.policySignals?.dataCollected || []).forEach((item) => values.add(item.label)); return [...values]; }
export function localSharedWithSummary(report) { const values = new Set(); const categories = new Set((report?.thirdParties || []).flatMap((party) => party.categories || [])); const names = { analytics: "analytics vendors", ads: "advertising partners", identity: "sign-in services", consent: "cookie consent tools", support: "support providers" }; Object.entries(names).forEach(([key, value]) => { if (categories.has(key)) values.add(value); }); if (report?.thirdParties?.length) values.add("service providers"); (report?.content?.policySignals?.sharing || []).forEach((item) => values.add(item.label)); return [...values]; }

export function renderPrivacyLabel(report, analysis, { confidenceSummary }) {
  const node = el("privacyLabel"); node.replaceChildren(); const policy = analysis?.policy; const confidence = confidenceSummary(report, analysis);
  if (policy?.privacyLabel) { const label = policy.privacyLabel; const collected = analysis.source === "local" ? localDataCollectedSummary(report).join(", ") || "Not visible from the current page" : label.collects.join(", ") || "none detected"; const shared = analysis.source === "local" ? localSharedWithSummary(report).join(", ") || "Not visible from the current page" : label.shares.join(", ") || policy.saleOrSharing; node.append(labelItem("Privacy grade", label.grade, `${policy.risk.level} policy risk`), labelItem("Confidence", confidence.label, confidence.detail), labelItem("Data collected", collected, analysis.source === "local" ? "page-level estimate" : "from policy text"), labelItem("Shared or sold", shared, analysis.source === "local" ? "page-level estimate" : "evidence-based"), labelItem("Retention", policy.retention?.[0] || label.retention, "policy wording"), labelItem("AI training", policy.aiTraining || "No explicit mention detected", "policy wording"), labelItem("Rights", label.rights.length ? label.rights.slice(0, 2).join("; ") : "Review region", "plain-language guide")); return; }
  node.append(labelItem("Privacy grade", "Pending", "click Build label"), labelItem("Confidence", confidence.label, confidence.detail), labelItem("Data collected", "Open the policy to confirm", "from the page"), labelItem("Shared with", "Open the policy to confirm", "from the page"), labelItem("Third parties", String(report?.thirdParties?.length || 0), "network and page hints"), labelItem("AI training", "Unknown", "needs policy analysis"), labelItem("Retention", "Unknown", "needs policy analysis"));
}

export function renderSiteIntelligence(report, { resolvePartyIntel, friendlyCategory }) {
  const node = el("siteIntelligence"); node.replaceChildren(); const merged = (report?.thirdParties || []).map(resolvePartyIntel); const companies = [...new Set(merged.filter((item) => item.company && item.company !== "Unidentified service").map((item) => item.company))].slice(0, 4); const known = merged.filter((item) => item.known).length; const categories = new Map(); (report?.thirdParties || []).forEach((party) => (party.categories?.length ? party.categories : ["unknown"]).forEach((category) => categories.set(category, (categories.get(category) || 0) + 1))); const top = [...categories.entries()].sort((a, b) => b[1] - a[1])[0]; node.append(labelItem("Website", report?.pageHost || "Unknown", "active tab"), labelItem("Companies involved", companies.length ? companies.join(", ") : "No company match yet", known ? `${known} known mappings` : "Needs a richer database"), labelItem("Main service type", top ? friendlyCategory(top[0]) : "Unknown", top ? `${top[1]} domain${top[1] === 1 ? "" : "s"} seen` : "No category yet"), labelItem("Recommended action", report?.risk?.level === "High" ? "Review before accepting" : "Keep monitoring", report?.risk?.level === "High" ? "High risk" : `${report?.risk?.level || "Low"} risk"));
}
